server {
    # CORREGIDO: Escucha en el 8000 para evitar bloqueos de privilegios en Fargate
    listen 8000;
    server_name localhost;

    # Ruta para los archivos estáticos del Frontend (HTML, JS, CSS)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # PROXY INVERSO PARA VENTAS: Redirige /api/v1/ventas al puerto 8080
    location /api/v1/ventas {
        proxy_pass http://localhost:8080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # PROXY INVERSO PARA DESPACHOS: Redirige /api/v1/despachos al puerto 8081
    location /api/v1/despachos {
        proxy_pass http://localhost:8081;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}