name: Deploy innovatech en la nube

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECS_CLUSTER: eva-2-cluster
  ECS_SERVICE: app-service

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login en ECR de AWS
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Backend de ventas
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build --platform linux/amd64 \
          --build-arg SPRING_DATASOURCE_URL=jdbc:mysql://127.0.0.1:3306/innovatech_db \
          --build-arg SPRING_DATASOURCE_USERNAME=root \
          --build-arg SPRING_DATASOURCE_PASSWORD=root_password \
          -t $ECR_REGISTRY/eva-2-back-ventas:latest \
          ./back-ventas
          
      - name: Push Backend ventas
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $ECR_REGISTRY/eva-2-back-ventas:latest

      - name: Build Backend despacho
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build --platform linux/amd64 \
          --build-arg SPRING_DATASOURCE_URL=jdbc:mysql://127.0.0.1:3306/innovatech_db \
          --build-arg SPRING_DATASOURCE_USERNAME=root \
          --build-arg SPRING_DATASOURCE_PASSWORD=root_password \
          -t $ECR_REGISTRY/eva-2-back-despachos:latest \
          ./back-despachos

      - name: Push Backend despacho
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $ECR_REGISTRY/eva-2-back-despachos:latest

      - name: Build frontend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build --platform linux/amd64 \
          -t $ECR_REGISTRY/eva-2-frontend:latest \
          ./front_despacho

      - name: Push frontend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $ECR_REGISTRY/eva-2-frontend:latest

      - name: Redesplegar Aplicación Unificada en ECS
        run: |
          aws ecs update-service \
          --cluster ${{ env.ECS_CLUSTER }} \
          --service ${{ env.ECS_SERVICE }} \
          --force-new-deployment \
          --region ${{ env.AWS_REGION }}